### PR TITLE
Handle comments within a block

### LINKED ISSUE #136: Comments wrongly converted in lists
I am using [Hugo](github.com/spf13/hugo), and encountered the bug detailed below. I am told blackfriday is the markdown parser used by Hugo, so I am reporting the bug here too.

Within a list (e.g., `<DL>` `</DL>`) in a markdown document, Hugo converts comments (`<!-- -->`) to `&lt;!&ndash; &ndash;&gt;`. Outside the list scope the comments are treated correctly and left as comments (`<!-- -->`). This is a bug.

I first observed this bug in definition lists, but it turns out all lists are affected, including markdown lists demarcated with `-` or `*`, not just HTML tagged lists, with the comments incorrectly rendered, turning them into displayed characters. The bug can be circumvented by separating the comments from the list using copious amounts of blank lines, but these blank lines then appear in the HTML affecting the layout of the list.

Refers  to spf13/hugo#729.

### PR DESCRIPTION
**Pull request by rtfb**
Added test cases both for inline and block workflows.

Closes #136.

### CODE REVIEW

File: inline_test.go [hunk 1]
```diff
@@ -973,6 +973,28 @@ func TestFootnotesWithParameters(t *testing.T) {
...
+		"Hello <!---->\n",
+		"<p>Hello <!----></p>\n",
+		"Hello <!-- there -->\na",
+		"<p>Hello <!-- there -->\na</p>\n",
+		"* list <!-- item -->\n",
+		"<ul>\n<li>list <!-- item --></li>\n</ul>\n",
+		"<!-- Front --> comment\n",
+		"<p><!-- Front --> comment</p>\n",
+		"blahblah\n<!--- foo -->\nrhubarb\n",
+		"<p>blahblah\n<!--- foo -->\nrhubarb</p>\n",
```
Comment (shurcooL) [inline inline_test.go]: Maybe it's a good idea to separate each test case (input and expected output) with a blank line, for better readability and consistency with existing code. See [here](https://github.com/russross/blackfriday/blob/1d673b3cd9cc47e45ced0b25a9aa191dbf8cfbd8/inline_test.go#L162-L181) for example.

File: block_test.go [hunk 2]
```diff
@@ -1401,7 +1401,17 @@ func TestTitleBlock_EXTENSION_TITLEBLOCK(t *testing.T) {
...
+}
 
+func TestBlockComments(t *testing.T) {
+	var tests = []string{
+		"Some text\n\n<!-- comment -->\n",
+		"<p>Some text</p>\n\n<!-- comment -->\n",
+		"Some text\n\n<!--\n\nmultiline\ncomment\n-->\n",
+		"<p>Some text</p>\n\n<!--\n\nmultiline\ncomment\n-->\n",
+		"Some text\n\n<!--\n\n<div><p>Commented</p>\n<span>html</span></div>\n-->\n",
+		"<p>Some text</p>\n\n<!--\n\n<div><p>Commented</p>\n<span>html</span></div>\n-->\n",
```
Comment (shurcooL) [inline block_test.go]: Here as well.

**Comment by shurcooL** [comment]
Minor code style comment in test cases.

Otherwise LGTM. But this dealing with HTML within Markdown stuff is not trivial...
